### ISSUE TITLE
64-bit ARM binaries

### ISSUE THREAD

**Issue by speedst3r** [mikenye/docker-radarbox#29]
Looks like Radarbox now make 64-bit ARM binaries available, and a user on FA discussions has a 64-bit MLAT client.

https://discussions.flightaware.com/t/howto-install-piaware-3-8-1-on-64-bit-raspbian-os-pi4/65477/26?u=abcd567

Raising issue as per README.md 😁

**Comment by mikenye** [comment]
Hi @speedst3r, thanks for the info. I'll take a look at this asap.

**Comment by mikenye** [comment]
Hi @speedst3r, if you pull the latest version of `mikenye/radarbox:latest`, this uses native 64-bit ARM binaries (if you run on an ARM64 platform). Thanks!

**Comment by speedst3r** [comment]
Thanks, still waiting for my SDR and antenna to arrive but have my K8s manifests ready to go.

(good to see a fellow WA station!)
