### ISSUE TITLE
Update container to rbfeeder v0.4.2

### ISSUE THREAD

**Issue by 76rhodan** [mikenye/docker-radarbox#44]
I got a mail (added below) from RB, announcing a new build for rbfeeder. As the weather data is pulled from the ADSB data and no extra hardware is required, maybe it's worthwhile to supply them with the extra data :-)

> Dear RadarBox Feeder,
> 
> AirNav Systems is pleased to announce the release of a new Raspberry Pi
> build (software update) for feeders sharing data with RadarBox.com. The new
> build (v0.4.2) allows for weather data to be collected from the ADS-B data
> sent by your Raspberry Pi.
> 
> The weather data that is collected from your Raspberry Pi ADS-B data
> includes:
> 
>    1. Air Temperature
>    2. Wind Speed
>    3. Wind Direction
> 
> Once collected, the weather data is then processed and used to build
> and improve the RadarBox Global Weather Model. Attached to this email are 3
> screenshots of how your Raspberry Pi weather data helps build our weather
> models. Please note that no other personal or private data is collected.
> Updating your Raspberry Pi to this build (v0.4.2) is purely optional and
> voluntary, although it is highly recommended.
> 
> Feeders who have set up their Raspberry Pi and started sharing data with
> RadarBox.com after May 24, 2021 have automatically received the update and
> do not need to update their build version. However, feeders who have set up
> their Raspberry Pi prior to, or on, May 24, 2021 can follow the steps below
> to update their build version.
> 
> *STEPS *
> Open the Terminal app on your Raspberry Pi, then run each command below.
> 
>    1. sudo apt-get update
>    2. sudo apt-get install rbfeeder
>    3. sudo systemctl restart rbfeeder
> 
> After running the last command (#3), your Raspberry Pi should automatically
> restart and have the latest build installed.
>

**Comment by mikenye** [comment]
It looks like RB forgot to change the version in the binary…

```
root@e6af714b99fe:/# apt upgrade rbfeeder:armhf
Reading package lists... Done
Building dependency tree
Reading state information... Done
rbfeeder:armhf is already the newest version (0.4.2-20210525101900).
root@e6af714b99fe:/# rbfeeder --version
RBFeeder v0.4.1 (build 20210525102300)
```

Maybe instead of getting the version of rbfeeder from the binary, I need to get it from the package info…
